"""Human labels, help text and sections for the panel's Settings page (GET /api/settings)."""

SECTIONS: list[tuple[str, str, str]] = [
    ("general", "General", "Welcome channel and the role new members get."),
    ("ai", "AI support & /ask", "Who can use the AI helper, how it replies, and where /ask works."),
    ("tickets", "Tickets", "Ticket categories, limits and transcripts."),
    ("moderation", "Moderation", "Mod log, warn ladder, DMs, appeals, reports, lockdown, raid guard and the weekly digest."),
    ("automod", "Automod filters", "Filter thresholds, domains and exemptions. These are also editable on the Automod page."),
    ("patreon", "Patreon", "Patreon campaign, supporter roles and the Patreon channels."),
    ("announcements", "Announcements & releases", "Translated announcements, language roles, releases, CurseForge and patch notes."),
    ("devbuilds", "Dev builds & bug reports", "Dev jar downloads, the build gate and bug-report triage."),
    ("community", "Community", "Power Level leveling and the showcase board."),
    ("advanced", "Advanced", "Infrastructure: panel access, database, AI models and budgets, GitHub, webhooks, paths and logging."),
]

META: dict[str, tuple[str, str, str]] = {
    # General
    "welcome_channel_id": ("general", "Welcome channel", "Channel where new members get a welcome message once they pass membership screening; empty = no message."),
    "member_role_id": ("general", "Member role", "Role given to new members once they pass membership screening."),
    "member_role_name": ("general", "Member role name", "Role name looked up instead when no member role is picked."),
    "bot_restart_channel_id": ("general", "Bot restart channel", "Not read by any feature at the moment."),
    # AI support & /ask
    "ai_support_enabled": ("ai", "AI support", "Lets the AI answer in tickets, DMs and mentions; off silences it everywhere."),
    "ai_support_allowed_role_ids": ("ai", "AI support roles", "Members with any of these roles can ask the AI by DM or mention; staff always can, ticket owners always get answers."),
    "ai_support_history_limit": ("ai", "Conversation history", "How many recent channel messages the AI reads before replying."),
    "ai_support_timeout_seconds": ("ai", "Reply timeout", "Seconds to wait for an AI reply before giving up."),
    "ai_support_typing_lead_seconds": ("ai", "Typing delay", "Seconds the bot shows \"typing…\" before posting an AI reply; 0 posts right away."),
    "ai_support_debounce_seconds": ("ai", "Message debounce", "Seconds to wait for more messages from the same person before the AI replies, so split messages get one answer."),
    "ai_support_escalation_confidence": ("ai", "Escalation confidence", "A first-pass answer below this confidence (0 to 1) gets a second opinion from the bigger model."),
    "ai_ticket_resolve_min_confidence": ("ai", "\"Solved?\" prompt: minimum confidence", "Below this AI confidence (0 to 1) a ticket never gets the \"Have I solved your problem?\" buttons."),
    "ai_ticket_resolve_prompt_exponent": ("ai", "\"Solved?\" prompt: curve", "Chance of the \"solved?\" buttons is confidence to this power; higher asks less often (3: 0.8 confidence → 51%)."),
    "ai_ticket_escalation_role_ids": ("ai", "Escalation roles", "Roles pinged in a ticket when the member says the AI didn't solve it."),
    "ask_allowed_channel_ids": ("ai", "/ask channels", "Channels where /ask can be used; empty = nowhere."),
    "ask_rate_limit_window_seconds": ("ai", "/ask rate limit: window", "Length in seconds of the window for the per-person /ask limit."),
    "ask_rate_limit_max_calls": ("ai", "/ask rate limit: calls", "How many /ask uses one person gets per window."),
    # Tickets
    "ai_ticket_category_id": ("tickets", "Open tickets category", "Category that holds open tickets; the AI answers there and reopened tickets move back to it."),
    "ticket_closed_category_id": ("tickets", "Closed tickets category", "Category closed tickets are moved to."),
    "ticket_max_open_per_user": ("tickets", "Open tickets per member", "How many open tickets one member can have at a time."),
    "ticket_dm_transcript": ("tickets", "DM transcript link", "DM the ticket owner a link to the hosted transcript when their ticket is archived."),
    "ticket_transcript_retention_days": ("tickets", "Transcript retention", "Days a hosted ticket transcript stays online; 0 keeps them forever."),
    "ai_ticket_close_delay_seconds": ("tickets", "Delete delay", "Seconds between the close notice and the ticket channel being deleted."),
    # Moderation
    "moderation_enabled": ("moderation", "Automod & raid guard", "Master switch: off stops every automod filter and the raid guard."),
    "moderation_log_channel_id": ("moderation", "Moderation log channel", "Channel for automod alerts and mod actions; also the fallback for appeals and reports, and where bot warnings are forwarded."),
    "moderation_warn_ladder": ("moderation", "Warn ladder", "What active warns lead to, as \"count[/window]=action\" pairs, e.g. 1=1h, 2=1d, 3=3d, 4=ban:7d; the highest matched step wins."),
    "moderation_warn_expiry": ("moderation", "Warn expiry", "How long the 1st, 2nd, 3rd… active warn lasts, e.g. 2w, 3w, 4w, 60d; the last value covers every later warn."),
    "moderation_dm_on_action": ("moderation", "DM on action", "DM members when they are warned, timed out, kicked or banned."),
    "moderation_appeals_enabled": ("moderation", "Ban appeals", "Adds an appeal button to ban DMs and accepts appeals."),
    "moderation_appeals_channel_id": ("moderation", "Appeals channel", "Channel where ban appeals are posted; empty = the moderation log channel."),
    "moderation_reports_channel_id": ("moderation", "Reports channel", "Channel where member reports are posted; empty = the moderation log channel."),
    "moderation_lockdown_channel_ids": ("moderation", "Lockdown channels", "Channels locked by a lockdown; empty = every text channel @everyone can talk in."),
    "moderation_raid_join_count": ("moderation", "Raid: joins", "This many joins inside the raid window turns on raid mode."),
    "moderation_raid_join_window_seconds": ("moderation", "Raid: window", "Length in seconds of the window used to count joins for raid detection."),
    "moderation_raid_mode_minutes": ("moderation", "Raid mode length", "Minutes raid mode lasts; each new join during a raid restarts the timer."),
    "moderation_raid_action": ("moderation", "Raid: action", "What happens to each member joining during raid mode: alert, timeout (1 hour) or kick."),
    "moderation_new_account_days": ("moderation", "New account age", "Accounts younger than this many days are flagged when they join."),
    "moderation_new_account_action": ("moderation", "New account action", "What happens to a flagged new account on join: alert, timeout (1 day) or kick."),
    "moderation_digest_enabled": ("moderation", "Weekly digest", "Posts a moderation digest every Monday."),
    "moderation_digest_channel_id": ("moderation", "Digest channel", "Channel for the weekly digest; empty = the text channel named staff-general."),
    # Automod filters
    "moderation_excluded_channel_ids": ("automod", "Ignored channels", "Automod never checks messages in these channels."),
    "moderation_exempt_role_ids": ("automod", "Exempt roles", "Members with any of these roles are never checked; staff and admins always are exempt."),
    "moderation_disabled_filters": ("automod", "Disabled filters", "Filter ids switched off on the Automod page; their thresholds are kept."),
    "moderation_filter_rules": ("automod", "Per-filter rules", "JSON of per-filter exempt channels, exempt roles and action override, written by the Automod page."),
    "moderation_blocked_domains": ("automod", "Blocked domains", "Links to these domains are deleted and stripped from AI replies (comma-separated)."),
    "moderation_allowed_domains": ("automod", "Always-allowed domains", "Trusted domains, skipped by the PhishDestroy lookup; a blocked domain still wins (comma-separated)."),
    "moderation_block_discord_invites": ("automod", "Block invite links", "Deletes Discord server invite links."),
    "moderation_image_burst_count": ("automod", "Image burst: images", "Images inside the window that trigger the image-burst timeout; 0 turns the filter off."),
    "moderation_image_burst_window_seconds": ("automod", "Image burst: window", "Length in seconds of the window used to count images."),
    "moderation_image_burst_min_messages": ("automod", "Image burst: minimum messages", "The images must be spread over at least this many messages to count as a burst."),
    "moderation_image_burst_timeout_seconds": ("automod", "Image burst: timeout length", "Seconds the member is timed out for when the image-burst filter fires."),
    "moderation_image_burst_purge_seconds": ("automod", "Image burst: purge window", "Seconds of their recent messages, in every channel, deleted when the image-burst filter fires."),
    "moderation_link_burst_count": ("automod", "Link burst: links", "Clickable links inside the window that trigger a timeout; 0 turns the filter off."),
    "moderation_link_burst_window_seconds": ("automod", "Link burst: window", "Length in seconds of the window used to count links."),
    "moderation_banned_words": ("automod", "Banned words", "Messages with these words are deleted and AI replies with them are blocked; * is a wildcard (comma-separated)."),
    "moderation_mass_mention_limit": ("automod", "Mass mention limit", "Messages with this many user or role mentions are deleted; 0 turns it off."),
    "moderation_block_everyone_ping": ("automod", "Block @everyone / @here", "Deletes @everyone and @here from members who aren't allowed to use them."),
    "moderation_duplicate_count": ("automod", "Duplicates: copies", "The same message sent this many times inside the window is deleted (timeout if spread over channels); 0 turns it off."),
    "moderation_duplicate_window_seconds": ("automod", "Duplicates: window", "Length in seconds of the window used to count duplicate messages."),
    "moderation_fast_message_count": ("automod", "Fast messages: count", "Messages from one member inside the window that count as too fast; 0 turns it off."),
    "moderation_fast_message_window_seconds": ("automod", "Fast messages: window", "Length in seconds of the window used to count fast messages."),
    "moderation_caps_percent": ("automod", "Caps: percent", "Messages with at least this percentage of capital letters are deleted; 0 turns it off."),
    "moderation_caps_min_length": ("automod", "Caps: minimum letters", "The caps check only looks at messages with at least this many letters."),
    "moderation_emoji_limit": ("automod", "Emoji limit", "Messages with this many emoji are deleted; 0 turns it off."),
    "moderation_newline_limit": ("automod", "Line break limit", "Messages with this many line breaks outside code blocks are deleted; 0 turns it off."),
    "moderation_zalgo_enabled": ("automod", "Block zalgo text", "Deletes glitchy zalgo text."),
    "moderation_scam_images_enabled": ("automod", "Scam images", "Matches posted images against the saved scam pictures by image hash."),
    "moderation_scam_images_enforce": ("automod", "Scam images: delete", "Deletes scam-image matches; off only posts a review alert."),
    "moderation_scam_image_distance": ("automod", "Scam images: match distance", "How many bits (out of 64) an image hash may differ and still match; lower is stricter."),
    "phishdestroy_enabled": ("automod", "PhishDestroy checks", "Checks posted link domains against the PhishDestroy threat list."),
    "phishdestroy_action": ("automod", "PhishDestroy action", "What to do with a flagged link: alert (staff only) or delete."),
    "phishdestroy_timeout_seconds": ("automod", "PhishDestroy timeout", "Seconds to wait for a PhishDestroy lookup."),
    "phishdestroy_safe_ttl_seconds": ("automod", "PhishDestroy safe cache", "Seconds a \"safe\" PhishDestroy verdict is cached."),
    "phishdestroy_threat_ttl_seconds": ("automod", "PhishDestroy threat cache", "Seconds a \"threat\" PhishDestroy verdict is cached."),
    "phishdestroy_recovery_interval_seconds": ("automod", "PhishDestroy retry interval", "Seconds between retries while the PhishDestroy API is down (at least 60)."),
    # Patreon
    "PATREON_CAMPAIGN_ID": ("patreon", "Campaign ID", "Patreon campaign polled for new posts and checked for memberships."),
    "patreon_eligible_tier_ids": ("patreon", "Eligible tiers", "Patreon tier ids that grant beta access (comma-separated)."),
    "patreon_access_role_ids": ("patreon", "Supporter roles", "Discord roles that mark someone as a Patreon supporter (beta access, private /ask answers)."),
    "patreon_contributor_role_id": ("patreon", "Contributor role", "Supporters with this role can gift beta access to 1 person."),
    "patreon_benefactor_role_id": ("patreon", "Benefactor role", "Supporters with this role can gift beta access to 2 people."),
    "patreon_admin_ping_role_id": ("patreon", "Admin ping role", "Not read by any feature at the moment."),
    "patreon_bot_user_id": ("patreon", "Patreon bot user", "User id of the Patreon bot; its role grants trigger the supporter welcome."),
    "patreon_welcome_channel_id": ("patreon", "Welcome channel", "Channel where new Patreon supporters are welcomed."),
    "patreon_announcement_channel_id": ("patreon", "Patreon posts channel", "Channel where new Patreon posts are announced (and auto-published)."),
    # Announcements & releases
    "announcement_source_channel_id": ("announcements", "Source announcements channel", "Admin posts here are translated to Spanish and Portuguese and auto-published."),
    "announcement_spanish_channel_id": ("announcements", "Spanish channel", "Channel that receives the Spanish translation of announcements."),
    "announcement_portuguese_channel_id": ("announcements", "Portuguese channel", "Channel that receives the Portuguese translation of announcements."),
    "announcement_role_en_id": ("announcements", "English ping role", "English announcement role; translations swap its mention for the matching language role."),
    "announcement_role_es_id": ("announcements", "Spanish ping role", "Role mentioned in Spanish translations in place of the English role."),
    "announcement_role_pt_id": ("announcements", "Portuguese ping role", "Role mentioned in Portuguese translations in place of the English role."),
    "releases_channel_id": ("announcements", "Releases channel", "Channel where release candidates are posted for approval; messages here are auto-published."),
    "sneak_peeks_channel_id": ("announcements", "Sneak peeks channel", "Messages posted here are auto-published to following servers."),
    "curseforge_enabled": ("announcements", "CurseForge updates", "Polls CurseForge and announces new files."),
    "curseforge_project_id": ("announcements", "CurseForge project ID", "Numeric CurseForge project id to watch."),
    "curseforge_project_slug": ("announcements", "CurseForge project slug", "Project path used for curseforge.com links, e.g. minecraft/mc-mods/dragonminez."),
    "curseforge_announcement_channel_id": ("announcements", "CurseForge channel", "Channel where new CurseForge files are announced; empty turns the updater off."),
    "curseforge_poll_minutes": ("announcements", "CurseForge poll interval", "Minutes between CurseForge checks."),
    "patch_notes_repo": ("announcements", "Patch notes repo", "GitHub repository that holds the patch notes."),
    "patch_notes_branch": ("announcements", "Patch notes branch", "Branch the patch notes are read from; changes are announced to the dev jar channels."),
    # Dev builds & bug reports
    "dev_jar_download_enabled": ("devbuilds", "Dev jar downloads", "Accepts dev jar uploads from CI and serves one-time download links."),
    "dev_jar_review_channel_id": ("devbuilds", "Review channel", "Staff channel where each new dev jar waits for approval before it is announced; empty = nothing is published."),
    "dev_jar_announcement_channel_ids": ("devbuilds", "Announcement channels", "Channels where approved dev jars and patch notes updates are announced."),
    "dev_jar_download_channel_id": ("devbuilds", "Downloads channel", "Channel linked from the Patreon welcome DM as the place to download dev jars."),
    "dev_jar_patreon_role_ids": ("devbuilds", "Download roles: Patreon", "Patreon roles allowed to download dev jars."),
    "dev_jar_tester_role_ids": ("devbuilds", "Download roles: testers", "Tester roles allowed to download dev jars; they also count as testers for beta access and the AI."),
    "dev_jar_download_token_ttl_seconds": ("devbuilds", "Download link lifetime", "Seconds a one-time download link stays valid."),
    "build_gate_enabled": ("devbuilds", "Build gate", "A Java push asks staff whether to build a dev jar before the workflow runs."),
    "build_gate_channel_id": ("devbuilds", "Build gate channel", "Channel for build gate prompts; empty = the dev jar review channel."),
    "build_gate_workflow": ("devbuilds", "Build workflow", "GitHub Actions workflow file dispatched when a build is approved."),
    "build_gate_expire_minutes": ("devbuilds", "Prompt expiry", "Minutes before an unanswered build prompt closes itself."),
    "build_gate_window_minutes": ("devbuilds", "Merge window", "Pending pushes to the same branch within this many minutes are merged into one prompt."),
    "bug_reports_enabled": ("devbuilds", "Bug-report triage", "AI triage of new bug-report forum posts and tracking of their GitHub issues."),
    "bug_report_forum_channel_id": ("devbuilds", "Bug-report forum", "Forum channel whose new posts are triaged; empty turns triage off."),
    "bug_report_repo": ("devbuilds", "Bug-report repo", "GitHub repository searched for matching issues."),
    "bug_report_poll_minutes": ("devbuilds", "Issue poll interval", "Minutes between checks of tracked GitHub issues."),
    # Community
    "power_level_enabled": ("community", "Power Level", "Members gain Power Level from chatting."),
    "power_level_excluded_channel_ids": ("community", "Excluded channels", "Messages in these channels earn no Power Level."),
    "power_level_role_rewards": ("community", "Role rewards", "JSON object of level → role id, e.g. {\"10\": \"123…\"}; the role is given on reaching that level."),
    "power_level_leaderboard_size": ("community", "Leaderboard size", "Default number of members shown by the leaderboard command."),
    "showcase_source_channel_ids": ("community", "Showcase source channels", "Channels whose posts can be highlighted."),
    "showcase_target_channel_id": ("community", "Showcase board channel", "Channel highlighted posts are copied to; empty turns the showcase off."),
    "showcase_reaction_emoji": ("community", "Showcase emoji", "Reaction that counts as a vote."),
    "showcase_threshold": ("community", "Showcase votes", "Votes needed (not the author, bots or brand-new accounts) to highlight a post."),
    # Advanced: panel and access
    "panel_enabled": ("advanced", "Admin panel", "Starts this web panel when the bot boots."),
    "panel_host": ("advanced", "Panel host", "Address the panel's web server binds to."),
    "panel_port": ("advanced", "Panel port", "Port the panel's web server listens on."),
    "panel_public_url": ("advanced", "Panel public URL", "Public address of the panel, used for the login redirect and the request origin check."),
    "panel_guild_id": ("advanced", "Main server", "The Discord server the panel and the bot's moderation manage."),
    "panel_owner_role_ids": ("advanced", "Panel owner roles", "Roles with owner access to the panel; they also act as moderators in tickets."),
    "panel_admin_role_ids": ("advanced", "Panel admin roles", "Roles with admin access to the panel; they also act as moderators in tickets."),
    "panel_moderator_role_ids": ("advanced", "Panel moderator roles", "Roles with moderator access to the panel and in tickets."),
    "panel_helper_role_ids": ("advanced", "Panel helper roles", "Roles with helper access to the panel and in tickets."),
    "discord_staff_role_ids": ("advanced", "Staff roles", "Roles treated as staff: exempt from automod, allowed to use the AI and to approve dev jars."),
    "discord_oauth_client_id": ("advanced", "Discord OAuth client ID", "Discord application id used for panel login and the beta-access sign-in."),
    "discord_oauth_redirect_uri": ("advanced", "Discord OAuth redirect", "Callback URL for the beta-access Discord sign-in."),
    "dev_guild_id": ("advanced", "Dev server", "Test server where slash commands register instantly and the bot also works; empty = none."),
    # Advanced: AI models and budget
    "openai_model": ("advanced", "Fallback model", "Mini model used for support when no support model is set and when the big-model budget is spent."),
    "openai_support_model": ("advanced", "Support model", "Model for the first, tool-free support reply."),
    "openai_support_escalation_model": ("advanced", "Escalation model", "Bigger model asked for a second opinion on unsure support replies."),
    "openai_support_reasoning_effort": ("advanced", "Reasoning effort", "Reasoning effort for escalated support replies (e.g. low, medium, high)."),
    "openai_support_fast_reasoning_effort": ("advanced", "Fast reasoning effort", "Reasoning effort for the first-pass support reply."),
    "openai_support_max_output_tokens": ("advanced", "Max output tokens", "Most tokens one AI support reply may use."),
    "openai_daily_small_token_limit": ("advanced", "Daily mini-model tokens", "Tokens per UTC day for mini/nano models; when spent the AI pauses until midnight UTC."),
    "openai_daily_big_token_limit": ("advanced", "Daily big-model tokens", "Tokens per UTC day for big models; when spent replies fall back to the mini model."),
    "openai_daily_billed_token_limit": ("advanced", "Daily billed tokens", "Tokens per UTC day for tool-using (billed) requests; when spent escalations run without tools."),
    "openai_support_vector_store_ids": ("advanced", "Support vector stores", "OpenAI vector store ids the support AI searches (comma-separated); closed tickets go to the first one by default."),
    "openai_support_file_search_max_results": ("advanced", "File search results", "Most results one file search returns; 0 uses OpenAI's default."),
    "openai_support_store_responses": ("advanced", "Store responses", "Asks OpenAI to store support responses; tool-using replies need this to chain rounds."),
    "openai_ticket_vector_store_id": ("advanced", "Ticket vector store", "Vector store closed tickets are uploaded to; empty = the first support vector store."),
    "openai_ticket_summary_model": ("advanced", "Ticket summary model", "Model that writes the summary when a ticket closes."),
    "openai_vision_model": ("advanced", "Vision model", "Model that reads images posted in support conversations."),
    "openai_translation_model": ("advanced", "Translation model", "Model that translates announcements."),
    "openai_bugreport_model": ("advanced", "Bug-report model", "Model that triages bug-report forum posts."),
    "openai_faq_suggestion_model": ("advanced", "FAQ suggestion model", "Model used by scripts/suggest_support_faq.py."),
    "openai_faq_vector_store_id": ("advanced", "FAQ vector store", "Vector store scripts/suggest_support_faq.py uploads to."),
    "openai_faq_generated_path": ("advanced", "FAQ output file", "Where scripts/suggest_support_faq.py writes the generated FAQ."),
    "openai_wiki_vector_store_id": ("advanced", "Wiki vector store", "Vector store scripts/sync_wiki_knowledge.py uploads the wiki to; empty = the first support vector store."),
    "wiki_git_url": ("advanced", "Wiki git URL", "Git URL scripts/sync_wiki_knowledge.py clones the wiki from."),
    "wiki_base_url": ("advanced", "Wiki URL", "Public wiki address; used for source links in AI replies, and links to it are trusted."),
    # Advanced: GitHub
    "GH_APP_ID": ("advanced", "GitHub App ID", "GitHub App the bot authenticates as."),
    "GH_INSTALLATION_ID": ("advanced", "GitHub App installation", "Installation id of the GitHub App on the organization."),
    "GITHUB_OWNER": ("advanced", "GitHub owner", "GitHub organization or user that owns the repositories."),
    "GITHUB_REPOS": ("advanced", "GitHub repositories", "Repositories the GitHub commands may use (comma-separated)."),
    "GITHUB_DEFAULT_REPO": ("advanced", "Default repository", "Repository used by GitHub commands when none is given, and watched by the build gate."),
    "GITHUB_BASE_BRANCH": ("advanced", "Base branch", "Base branch the bot's GitHub changes target; the build gate ignores pushes to it."),
    "GITHUB_WHITELIST_REPO": ("advanced", "Whitelist repository", "Repository that holds the beta tester whitelist file."),
    "GITHUB_WHITELIST_FILE_PATH": ("advanced", "Whitelist file", "Path of the beta tester whitelist file inside the whitelist repository."),
    "patch_notes_file_path": ("advanced", "Patch notes path", "Patch notes folder (newest versioned .md is used) or a specific .md file in the patch notes repo."),
    # Advanced: webhooks and URLs
    "release_webhook_enabled": ("advanced", "Webhook server", "Starts the webhook server (release candidates, dev jar uploads, build gate pushes, OAuth callbacks) at boot."),
    "release_webhook_host": ("advanced", "Webhook host", "Address the webhook server binds to."),
    "release_webhook_port": ("advanced", "Webhook port", "Port the webhook server listens on."),
    "release_webhook_path": ("advanced", "Release webhook path", "URL path that receives release-candidate webhooks."),
    "dev_jar_download_webhook_path": ("advanced", "Dev jar upload path", "URL path CI posts new dev jar uploads to."),
    "dev_jar_download_download_path": ("advanced", "Download path", "URL path of one-time dev jar download links."),
    "dev_jar_download_public_base_url": ("advanced", "Download base URL", "Public base URL for one-time dev jar download links."),
    "build_gate_webhook_path": ("advanced", "Build gate webhook path", "URL path that receives GitHub push webhooks for the build gate."),
    "phishdestroy_api_base_url": ("advanced", "PhishDestroy API URL", "Base URL of the PhishDestroy API."),
    "ticket_transcript_public_url": ("advanced", "Transcript public URL", "Public address hosted ticket transcripts are served from (/t/<token>)."),
    "ticket_transcript_dir": ("advanced", "Transcript folder", "Folder where hosted ticket transcripts are saved as HTML files."),
    "patreon_oauth_client_id": ("advanced", "Patreon OAuth client ID", "Patreon app id for the beta-access Patreon sign-in."),
    "patreon_oauth_redirect_uri": ("advanced", "Patreon OAuth redirect", "Callback URL for the beta-access Patreon sign-in."),
    # Advanced: database
    "PGHOST": ("advanced", "Database host", "PostgreSQL host, used when no PGDSN connection string is set."),
    "PGPORT": ("advanced", "Database port", "PostgreSQL port, used when no PGDSN connection string is set."),
    "PGUSER": ("advanced", "Database user", "PostgreSQL user, used when no PGDSN connection string is set."),
    "PGDB": ("advanced", "Database name", "PostgreSQL database, used when no PGDSN connection string is set."),
    # Advanced: bot runtime
    "initial_extensions": ("advanced", "Loaded cogs", "Python modules loaded as cogs at startup (comma-separated)."),
    "log_level": ("advanced", "Log level", "Logging level set at startup, e.g. INFO or DEBUG."),
    "discord_log_forwarding_enabled": ("advanced", "Forward logs to Discord", "Posts bot warnings and errors to the moderation log channel (read at startup)."),
    "discord_log_min_level": ("advanced", "Forwarded log level", "Lowest log level forwarded to Discord, e.g. WARNING."),
    "self_update_auto_apply": ("advanced", "Auto-apply updates", "Applies tested hot-reloadable updates from origin on their own; full restarts still ask first."),
    "message_presets_path": ("advanced", "Message presets path", "Its folder holds message_templates.json, the saved message templates."),
}


def humanize(name: str) -> str:
    text = name.replace("_", " ").strip()
    return text[:1].upper() + text[1:].lower() if text else name


def describe(name: str) -> tuple[str, str, str]:
    return META.get(name) or ("advanced", humanize(name), "")
